### ISSUE TITLE
App getting crashed with One plus one device

### ISSUE THREAD

**Issue by vishalgole** [BlinkID/blinkid-cordova#111]
Hi Team,

We have successfully integrated blink id plugin into application. But recently we found one issue. Users are not able to scan any id on one plus one ( A0001) device which is having android 8.1.0 version.

Application getting crash once user starts scanning. Its working fine on other devices.

**Comment by Cerovec** [comment]
Hi @vishalgole,

Apologies for the delay. This has been resolved with 4.10.0, so this should be fine now.

Complete release notes for 4.10.0 are here: https://github.com/BlinkID/blinkid-android/releases/tag/4.10.0

If you're still experiencing this problem, please reopen the issue.

Thanks!
Jurica.
