### ISSUE TITLE
Support for vertical USDL

### ISSUE THREAD

**Issue by ckang777** [BlinkID/blinkid-cordova#115]
Is there a way to scan vertical US driver licenses? I have made a work-around for this in the past but wondering if the newer version of the phonegap sdk will support this.

**Comment by culoi** [comment]
Hi @ckang777 

Last week we introduced a BlinkID v5 in which ,beside support for all 50 USA state, we support the vertical ID cards. At moment, this is available only for the native SDK ([iOS](https://github.com/BlinkID/blinkid-ios/blob/master/Release%20notes.md#500) and [Andorid](https://github.com/BlinkID/blinkid-android/blob/master/Release%20notes.md#500)). By the end of this week we will also support all supported crossplatforms (Cordova, Ionic, Phonegap, React Native, Xamarin). Please star and watch our repo to get an instant notification about v5 release for Phonegap.

Best regards

**Comment by Cerovec** [comment]
Hi @ckang777,

We support scanning the vertical IDs with USDLCombinedRecognizer in all of the new BlinkID SDK versions. Please let us know if we can help in any other way.

Thanks,
Jurica.
