### ISSUE TITLE
Build "MicroBlink.framework" failed. on xCode Version 12.x (macOS Big Sur)

### ISSUE THREAD

**Issue by eviv3k** [BlinkID/blinkid-cordova#142]
We have tried installing blinkid-cordova and got a error like couldn't download the Microblink framework, install wget.

To reproduce:
- ionic cordova plugin add blinkid-cordova

It fails with:

```
Installing "blinkid-cordova" for ios
Running hook: /Users/dev.admin/Documents/Vivek/TestApp/plugins/blinkid-cordova/scripts/initIOSFramework.sh /Users/dev.admin/Documents/Vivek/TestApp
ERROR: couldn't download Microblink framework, install wget
Failed to install 'blinkid-cordova': Error: Command failed with exit code 1: /Users/dev.admin/Documents/Vivek/TestApp/plugins/blinkid-cordova/scripts/initIOSFramework.sh /Users/dev.admin/Documents/Vivek/TestApp
    at makeError (/usr/local/lib/node_modules/cordova/node_modules/execa/lib/error.js:59:11)
    at handlePromise (/usr/local/lib/node_modules/cordova/node_modules/execa/index.js:114:26)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
Command failed with exit code 1: /Users/dev.admin/Documents/Vivek/TestApp/plugins/blinkid-cordova/scripts/initIOSFramework.sh /Users/dev.admin/Documents/Vivek/TestApp
```

Version:
- xCode 12 & macOS Big Sur
- blinkid-cordova 5.11.0
- Cordova iOS 6.2.0 (Cordova 10.0.0)

Hope to get a good reply soon.

Thanks in advance.

**Comment by mparadina** [comment]
Hi @eviv3k 

Just to double-check, did you install `wget`?

If you have Homebrew, you can install it by entering this command in the Terminal:
`brew install wget`

Also to ask, do you have Git LFS installed?

Regards,
Milan

**Comment by eviv3k** [comment]
Hi Milan,
No, I didn't install `wget` & `homebrew`. I am trying to install it. 
Yes, I have installed Git LFS. And get back to you.

Thanks

**Comment by mparadina** [comment]
Hi @eviv3k 

Yes, installing `wget` should fix the issue!

Let me know if that helped.

Regards,
Milan

**Comment by eviv3k** [comment]
Hi Milan, Thanks it works for me.
