### ISSUE TITLE
unable to get face image

### ISSUE THREAD

**Issue by taufpate** [BlinkID/blinkid-cordova#145]
faceImage and fullDocumentFrontImage returns 'undefined'

im using "blinkid-cordova": "^5.12.0",
`
scanMicroBlink(){

    let p = new Promise((resolve,reject) =>{

      var blinkIdCombinedRecognizer = new cordova.plugins.BlinkID.BlinkIdCombinedRecognizer();
      blinkIdCombinedRecognizer.returnFullDocumentImage = true;
      blinkIdCombinedRecognizer.returnFaceImage = true;
      blinkIdCombinedRecognizer.skipUnsupportedBack = true;
      blinkIdCombinedRecognizer.allowUncertainFrontSideScan = true;
      var blinkidOverlaySettings = new cordova.plugins.BlinkID.BlinkIdOverlaySettings();

      // create RecognizerCollection from any number of recognizers that should perform recognition
      var recognizerCollection = new cordova.plugins.BlinkID.RecognizerCollection([blinkIdCombinedRecognizer /*, mrtdSuccessFrameGrabber */]);

      // package name/bundleID com.microblink.blinkid

      cordova.plugins.BlinkID.scanWithCamera(cancelled=>{
          if (!cancelled) {
            console.error(blinkIdCombinedRecognizer)
          }else{
            reject()
          }
      },err=>{
        console.log('error scaning license 2');
        alert(JSON.stringify(err))
        reject(err)
        //
      },blinkidOverlaySettings, recognizerCollection, this.microBlink_licenseKeys,)
    });
    return p;

  }
`

**Comment by taufpate** [comment]
here the return:

`{
    "resultState": 3,
    "additionalAddressInformation": "",
    "additionalNameInformation": "",
    "address": "xxxx, FL, 33025-0000",
    "age": 43,
    "backImageAnalysisResult": {
        "blurred": false,
        "documentImageColorStatus": 1,
        "documentImageMoireStatus": 1,
        "faceDetectionStatus": 1,
        "mrzDetectionStatus": 1,
        "barcodeDetectionStatus": 1
    },
    "backProcessingStatus": 1,
    "backVizResult": {
        "firstName": "",
        "lastName": "",
        "fullName": "",
        "additionalNameInformation": "",
        "localizedName": "",
        "address": "",
        "additionalAddressInformation": "",
        "placeOfBirth": "",
        "nationality": "",
        "race": "",
        "religion": "",
        "profession": "",
        "maritalStatus": "",
        "residentialStatus": "",
        "employer": "",
        "sex": "",
        "documentNumber": "",
        "personalIdNumber": "",
        "documentAdditionalNumber": "",
        "additionalPersonalIdNumber": "",
        "issuingAuthority": "",
        "driverLicenseDetailedInfo": {
            "restrictions": "",
            "endorsements": "",
            "vehicleClass": "",
            "conditions": ""
        },
        "empty": true
    },
    "barcodeResult": {
        "barcodeType": 12,
        "rawData": "xxxxxxx",
        "uncertain": false,
        "firstName": "GUSTAVO",
        "lastName": "CARDOZO MORALES",
        "fullName": "CARDOZO MORALES,GUSTAVO",
        "middleName": "",
        "additionalNameInformation": "",
        "address": "xxxx, FL, 33025-0000",
        "placeOfBirth": "",
        "nationality": "",
        "race": "",
        "religion": "",
        "profession": "",
        "maritalStatus": "",
        "residentialStatus": "",
        "employer": "",
        "sex": "MALE",
        "dateOfBirth": {
            "day": 7,
            "month": 3,
            "year": 1978
        },
        "dateOfIssue": {
            "day": 6,
            "month": 6,
            "year": 2016
        },
        "dateOfExpiry": {
            "day": 7,
            "month": 3,
            "year": 2024
        },
        "documentNumber": "xxxx",
        "personalIdNumber": "",
        "documentAdditionalNumber": "",
        "issuingAuthority": "",
        "street": "xxxx",
        "postalCode": "33025-0000",
        "city": "MIRAMAR",
        "jurisdiction": "FL",
        "driverLicenseDetailedInfo": {
            "restrictions": "NONE",
            "endorsements": "NONE",
            "vehicleClass": "E",
            "conditions": ""
        },
        "extendedElements": {
            "empty": false,
            "values": [
                "AAMVA",
                "1",
                "CARDOZO MORALES",
                "GUSTAVO",
                "CARDOZO MORALES,GUSTAVO",
                "03071978",
                "1",
                "",
                "",
                "MIRAMAR",
                "FL",
                "33025-0000",
                ",
                "67 in",
                "67",
                "170",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "xxxx",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "N",
                "",
                "",
                "x",
                "x",
                "0",
                "E",
                "NONE",
                "NONE",
                "x",
                "",
                "ZF",
                "",
                "Florida",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                ""
            ]
        },
        "empty": false
    },
    "classInfo": {
        "country": 83,
        "region": 14,
        "type": 3,
        "countryName": "UNITED STATES OF AMERICA",
        "isoNumericCountryCode": "840",
        "isoAlpha2CountryCode": "US",
        "isoAlpha3CountryCode": "USA",
        "empty": false
    },
    "dateOfBirth": {
        "day": 7,
        "month": 3,
        "year": 1978
    },
    "dateOfExpiry": {
        "day": 7,
        "month": 3,
        "year": 2024
    },
    "dateOfExpiryPermanent": false,
    "dateOfIssue": {
        "day": 6,
        "month": 6,
        "year": 2016
    },
    "digitalSignature": "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==",
    "digitalSignatureVersion": 0,
    "documentAdditionalNumber": "",
    "documentDataMatch": 3,
    "documentNumber": "xxxx",
    "documentOptionalAdditionalNumber": "",
    "driverLicenseDetailedInfo": {
        "restrictions": "NONE",
        "endorsements": "NONE",
        "vehicleClass": "E",
        "conditions": ""
    },
    "employer": "",
    "expired": false,
    "firstName": "GUSTAVO",
    "frontImageAnalysisResult": {
        "blurred": false,
        "documentImageColorStatus": 1,
        "documentImageMoireStatus": 1,
        "faceDetectionStatus": 1,
        "mrzDetectionStatus": 1,
        "barcodeDetectionStatus": 1
    },
    "frontProcessingStatus": 1,
    "frontVizResult": {
        "firstName": "GUSTAVO",
        "lastName": "CARDOZO MORALES",
        "fullName": "",
        "additionalNameInformation": "",
        "localizedName": "",
        "address": "xxxx\nMIRAMAR, FL 33025-0000",
        "additionalAddressInformation": "",
        "placeOfBirth": "",
        "nationality": "",
        "race": "",
        "religion": "",
        "profession": "",
        "maritalStatus": "",
        "residentialStatus": "",
        "employer": "",
        "sex": "M",
        "dateOfBirth": {
            "day": 7,
            "month": 3,
            "year": 1978
        },
        "dateOfIssue": {
            "day": 6,
            "month": 6,
            "year": 2016
        },
        "dateOfExpiry": {
            "day": 7,
            "month": 3,
            "year": 2024
        },
        "documentNumber": "xxxx",
        "personalIdNumber": "",
        "documentAdditionalNumber": "",
        "additionalPersonalIdNumber": "",
        "issuingAuthority": "",
        "driverLicenseDetailedInfo": {
            "restrictions": "",
            "endorsements": "",
            "vehicleClass": "E",
            "conditions": ""
        },
        "empty": false
    },
    "fullName": "",
    "issuingAuthority": "",
    "lastName": "CARDOZO MORALES",
    "localizedName": "",
    "maritalStatus": "",
    "mrzResult": {
        "documentType": 1,
        "primaryId": "",
        "secondaryId": "",
        "issuer": "",
        "dateOfBirth": null,
        "documentNumber": "",
        "nationality": "",
        "gender": "",
        "documentCode": "",
        "dateOfExpiry": null,
        "opt1": "",
        "opt2": "",
        "alienNumber": "",
        "applicationReceiptNumber": "",
        "immigrantCaseNumber": "",
        "mrzText": "",
        "mrzParsed": false,
        "mrzVerified": false,
        "sanitizedOpt1": "",
        "sanitizedOpt2": "",
        "sanitizedNationality": "",
        "sanitizedIssuer": "",
        "sanitizedDocumentCode": "",
        "sanitizedDocumentNumber": ""
    },
    "nationality": "",
    "personalIdNumber": "",
    "placeOfBirth": "",
    "processingStatus": 1,
    "profession": "",
    "race": "",
    "recognitionMode": 6,
    "religion": "",
    "residentialStatus": "",
    "scanningFirstSideDone": true,
    "sex": "MALE"
}`

**Comment by taufpate** [comment]
here the return:
`
{
    "resultState": 3,
    "additionalAddressInformation": "",
    "additionalNameInformation": "",
    "address": "xxxx, FL, 33025-0000",
    "age": 43,
    "backImageAnalysisResult": {
        "blurred": false,
        "documentImageColorStatus": 1,
        "documentImageMoireStatus": 1,
        "faceDetectionStatus": 1,
        "mrzDetectionStatus": 1,
        "barcodeDetectionStatus": 1
    },
    "backProcessingStatus": 1,
    "backVizResult": {
        "firstName": "",
        "lastName": "",
        "fullName": "",
        "additionalNameInformation": "",
        "localizedName": "",
        "address": "",
        "additionalAddressInformation": "",
        "placeOfBirth": "",
        "nationality": "",
        "race": "",
        "religion": "",
        "profession": "",
        "maritalStatus": "",
        "residentialStatus": "",
        "employer": "",
        "sex": "",
        "documentNumber": "",
        "personalIdNumber": "",
        "documentAdditionalNumber": "",
        "additionalPersonalIdNumber": "",
        "issuingAuthority": "",
        "driverLicenseDetailedInfo": {
            "restrictions": "",
            "endorsements": "",
            "vehicleClass": "",
            "conditions": ""
        },
        "empty": true
    },
    "barcodeResult": {
        "barcodeType": 12,
        "rawData": "xxxxxxx",
        "uncertain": false,
        "firstName": "GUSTAVO",
        "lastName": "CARDOZO MORALES",
        "fullName": "CARDOZO MORALES,GUSTAVO",
        "middleName": "",
        "additionalNameInformation": "",
        "address": "xxxx, FL, 33025-0000",
        "placeOfBirth": "",
        "nationality": "",
        "race": "",
        "religion": "",
        "profession": "",
        "maritalStatus": "",
        "residentialStatus": "",
        "employer": "",
        "sex": "MALE",
        "dateOfBirth": {
            "day": 7,
            "month": 3,
            "year": 1978
        },
        "dateOfIssue": {
            "day": 6,
            "month": 6,
            "year": 2016
        },
        "dateOfExpiry": {
            "day": 7,
            "month": 3,
            "year": 2024
        },
        "documentNumber": "xxxx",
        "personalIdNumber": "",
        "documentAdditionalNumber": "",
        "issuingAuthority": "",
        "street": "xxxx",
        "postalCode": "33025-0000",
        "city": "MIRAMAR",
        "jurisdiction": "FL",
        "driverLicenseDetailedInfo": {
            "restrictions": "NONE",
            "endorsements": "NONE",
            "vehicleClass": "E",
            "conditions": ""
        },
        "extendedElements": {
            "empty": false,
            "values": [
                "AAMVA",
                "1",
                "CARDOZO MORALES",
                "GUSTAVO",
                "CARDOZO MORALES,GUSTAVO",
                "03071978",
                "1",
                "",
                "",
                "MIRAMAR",
                "FL",
                "33025-0000",
                ",
                "67 in",
                "67",
                "170",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "xxxx",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "N",
                "",
                "",
                "x",
                "x",
                "0",
                "E",
                "NONE",
                "NONE",
                "x",
                "",
                "ZF",
                "",
                "Florida",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                ""
            ]
        },
        "empty": false
    },
    "classInfo": {
        "country": 83,
        "region": 14,
        "type": 3,
        "countryName": "UNITED STATES OF AMERICA",
        "isoNumericCountryCode": "840",
        "isoAlpha2CountryCode": "US",
        "isoAlpha3CountryCode": "USA",
        "empty": false
    },
    "dateOfBirth": {
        "day": 7,
        "month": 3,
        "year": 1978
    },
    "dateOfExpiry": {
        "day": 7,
        "month": 3,
        "year": 2024
    },
    "dateOfExpiryPermanent": false,
    "dateOfIssue": {
        "day": 6,
        "month": 6,
        "year": 2016
    },
    "digitalSignature": "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==",
    "digitalSignatureVersion": 0,
    "documentAdditionalNumber": "",
    "documentDataMatch": 3,
    "documentNumber": "xxxx",
    "documentOptionalAdditionalNumber": "",
    "driverLicenseDetailedInfo": {
        "restrictions": "NONE",
        "endorsements": "NONE",
        "vehicleClass": "E",
        "conditions": ""
    },
    "employer": "",
    "expired": false,
    "firstName": "GUSTAVO",
    "frontImageAnalysisResult": {
        "blurred": false,
        "documentImageColorStatus": 1,
        "documentImageMoireStatus": 1,
        "faceDetectionStatus": 1,
        "mrzDetectionStatus": 1,
        "barcodeDetectionStatus": 1
    },
    "frontProcessingStatus": 1,
    "frontVizResult": {
        "firstName": "GUSTAVO",
        "lastName": "CARDOZO MORALES",
        "fullName": "",
        "additionalNameInformation": "",
        "localizedName": "",
        "address": "xxxx\nMIRAMAR, FL 33025-0000",
        "additionalAddressInformation": "",
        "placeOfBirth": "",
        "nationality": "",
        "race": "",
        "religion": "",
        "profession": "",
        "maritalStatus": "",
        "residentialStatus": "",
        "employer": "",
        "sex": "M",
        "dateOfBirth": {
            "day": 7,
            "month": 3,
            "year": 1978
        },
        "dateOfIssue": {
            "day": 6,
            "month": 6,
            "year": 2016
        },
        "dateOfExpiry": {
            "day": 7,
            "month": 3,
            "year": 2024
        },
        "documentNumber": "xxxx",
        "personalIdNumber": "",
        "documentAdditionalNumber": "",
        "additionalPersonalIdNumber": "",
        "issuingAuthority": "",
        "driverLicenseDetailedInfo": {
            "restrictions": "",
            "endorsements": "",
            "vehicleClass": "E",
            "conditions": ""
        },
        "empty": false
    },
    "fullName": "",
    "issuingAuthority": "",
    "lastName": "CARDOZO MORALES",
    "localizedName": "",
    "maritalStatus": "",
    "mrzResult": {
        "documentType": 1,
        "primaryId": "",
        "secondaryId": "",
        "issuer": "",
        "dateOfBirth": null,
        "documentNumber": "",
        "nationality": "",
        "gender": "",
        "documentCode": "",
        "dateOfExpiry": null,
        "opt1": "",
        "opt2": "",
        "alienNumber": "",
        "applicationReceiptNumber": "",
        "immigrantCaseNumber": "",
        "mrzText": "",
        "mrzParsed": false,
        "mrzVerified": false,
        "sanitizedOpt1": "",
        "sanitizedOpt2": "",
        "sanitizedNationality": "",
        "sanitizedIssuer": "",
        "sanitizedDocumentCode": "",
        "sanitizedDocumentNumber": ""
    },
    "nationality": "",
    "personalIdNumber": "",
    "placeOfBirth": "",
    "processingStatus": 1,
    "profession": "",
    "race": "",
    "recognitionMode": 6,
    "religion": "",
    "residentialStatus": "",
    "scanningFirstSideDone": true,
    "sex": "MALE"
}
`

**Comment by mparadina** [comment]
Hi @taufpate 

Which documents are you scanning?
Is the issue reproducible with every scan?

Also to ask, did you manage to reproduce this behaviour with the sample application?

Regards,
Milan

**Comment by taufpate** [comment]
Which documents are you scanning?
\US Drivers license

Is the issue reproducible with every scan?
\Yes, in android and ios and with multiple docs

Also to ask, did you manage to reproduce this behaviour with the sample application?
\No

**Comment by mparadina** [comment]
Hi @taufpate 

Is it possible for you to contact us directly at support@microblink.com?
I suspect that the reason why you're experiencing this behaviour could be because of the license key you're using in the project.

By contacting us directly, we can inspect the key and get a better view of the issue.

Regards,
Milan
