### ISSUE TITLE
In iOS, after scanning front and back, all images are undefined in BlinkIdMultiSideRecognizer.result

### ISSUE THREAD

**Issue by ckang777** [BlinkID/blinkid-cordova#155]
After successfully scanning both sides of the usdl driver license all images in result object is undefined only for iOS.
Works fine in Android.

```
var dlRecognizer = new cordova.plugins.BlinkID.BlinkIdMultiSideRecognizer();
dlRecognizer.numStableDetectionsThreshold = 10;
dlRecognizer.returnFaceImage = true;
dlRecognizer.returnFullDocumentImage = true;
documentOverlaySettings = new cordova.plugins.BlinkID.BlinkIdOverlaySettings();
recognizerCollection = new cordova.plugins.BlinkID.RecognizerCollection([dlRecognizer]);

// After successful scan
dlRecognizer.result.fullDocumentFrontImage  // undefined
dlRecognizer.result.fullDocumentBackImage // undefined
dlRecognizer.result.faceImage //undefined
dlRecognizer.result.signatureImage //undefined

```

![Screenshot 2023-06-30 at 3 12 51 PM](https://github.com/BlinkID/blinkid-cordova/assets/7827831/0a30991d-c2d7-43bf-9c02-8f99a919f2cc)

Please advise

**Comment by MBrizic01** [comment]
Hi @ckang777 , thank you for reaching out. Could you please send your inquiry to support@microblink.com? We'd like to know how you're handling the extraction of the image and the license key you're implementing. We want to troubleshoot this with you directly over email to facilitate communication. Thank you!
