### ISSUE TITLE
cordova plugin not scanning

### ISSUE THREAD

**Issue by VictorCoding** [BlinkID/blinkid-cordova#61]
Hello!

Thanks for this plugin, the demo works great(blinkID ios app from app store). However, I tried to implement it in my app with no success. The issue is that when I place the drivers license in the frame to scan, it's simply not scanning at all. Nothing happens. I tried tapping the screen that doesn't work either. I don't get any errors either. Im a bit lost here. Any help would be gladly appreciated. The following is the code snippet i'm using.

```
    const types = ["USDL"];
    const imageTypes = ["IMAGE_FACE"]
    const licenseKey = 'T3NW7MAE-KEX4X2OO-QKL2MZ5Q-JT5TK45F-SQWSKFKU-YQFTHSTI-6V6DBRMD-RA2QJHMV'

    window['cordova'].plugins.blinkIdScanner.scan((result) => {
      console.log(result)
    }, (err) => console.log(err), types, imageTypes, licenseKey, null, 'en')

**Comment by jcular** [comment]
Hi @VictorCoding,

sorry for delayed response,
if this issue persists could you describe in more detail are you trying to scan the front side of the USDL or the back side. Is there any log output?

Kind regards,
Jure

**Comment by salvadorhol** [comment]
@jcular 
I'm seeing same issue.
Nothing happens when placing the front of an ID card in the frame. 

@VictorCoding did you find a solution?

**Comment by VictorCoding** [comment]
@salvadorhol haven't found one yet 😢

**Comment by jcular** [comment]
Hi @salvadorhol,

@VictorCoding, in the sample you are using `USDL` recognizer which reads only the back side, to read the front side you need to use `DocumentFace`. I'm guessing that you are using an older version of the plugin, in the newer version combined recognziers are supported which allow you to scan the front side of usdl and then the back side.

Kind regards,
Jure

**Comment by Cerovec** [comment]
Hi @VictorCoding, @salvadorhol,

We're closing this issue as inactive. We've added several new features in the meantime, like UsdlCombinedRecognizer, which deals specifically with this functionality. If you need any other assistance, please reopen this or create another issue.

Thanks!
Jurica.
