### ISSUE TITLE
parse error

### ISSUE THREAD

**Issue by greggreenhaw** [BlinkID/blinkid-cordova#63]
I get the following error on prepare or build. I have tracked down the issue in IOS

Could not parse project.pbxproj: SyntaxError: Expected "/* Begin ", "/* End ", "\"", or [A-Za-z0-9_.] but "/" found.

In the main projects project.pbxproj file are the following entries for micro blink
Notice one is missing an inital hash value. removing the line stops the error

3B343CEC3B06493CBADD151A /* MicroBlink.framework in Frameworks */ = {isa = PBXBuildFile; fileRef = 8F702B9E9150485F8070A8F5 /* MicroBlink.framework */; };
		1E7B72F9C7B14E49BC58E8F0 /* MicroBlink.framework in Embed Frameworks */ = {isa = PBXBuildFile; fileRef = 8F702B9E9150485F8070A8F5 /* MicroBlink.framework */; settings = {ATTRIBUTES = (CodeSignOnCopy, ); }; };
		/* MicroBlink.framework in Embed Frameworks com.microblink.BlinkIdScanner */ = {isa = PBXBuildFile; fileRef = 8F702B9E9150485F8070A8F5 /* MicroBlink.framework */; settings = {ATTRIBUTES = (CodeSignOnCopy, RemoveHeadersOnCopy, ); }; };
		3C37E193AC6B45ADA1E45795 /* MicroBlink.framework in Frameworks */ = {isa = PBXBuildFile; fileRef = 8F702B9E9150485F8070A8F5 /* MicroBlink.framework */; };

**Comment by jkylehumphrey** [comment]
Also having this problem.

**Comment by greggreenhaw** [comment]
I removed the bad line and it built ok

**Comment by jkylehumphrey** [comment]
created a PR that seems to address this issue:

https://github.com/BlinkID/blinkid-phonegap/pull/67

**Comment by jcular** [comment]
Hi @jkylehumphrey and @greggreenhaw,

is this issue still relevant in the new version of the plugin, we tried to recreate it but it seems it's ok now. As for the PR I'll check it out if it works on the new version.

Kind regards,
Jure

**Comment by Cerovec** [comment]
Hi @greggreenhaw, @jkylehumphrey 

We're closing this issue as inactive. If you need any other assistance, please reopen this or create another issue.

Thanks!
Jurica.
