### ISSUE TITLE
Blurry Image, need only front image after 3 sec when back not scanning

### ISSUE THREAD

**Issue by jassiwalia001** [BlinkID/blinkid-cordova#80]
Through our test cases:

- We have came across some cases, in which we noticed that the image captured of the front of US Driving License is not clear and is blurred. Do we have any option by which we can get good clear image of the front which is stable & focused.
- In SDK we have chosen it to capture images at 400dpi, but its not same in output images. Those are of less quality. Can you help us with the exact pointers to correct this. (UsdlCombinedRecognizer: faceImageDpi, fullDocumentImageDpi & MrtdRecognizer: saveImageDPI)
- In some cases, where back of the US Driver's license is not scannable (QR Code is distorted/not clear), we are not able to save the front of the card. Do we have the option where after scanning front of the card, if back QR is not recognized in few seconds, it just captures image of the back of the card. So that we can save front & back of card in good quality image irrespective of card being old or new.

Please let me know, if you have any query related to above points.

**Comment by jcular** [comment]
Hi @jassiwalia001,

could you tell us the version of plugin and the platform(Android or iOS) that this issue appears on.

Kind regards,
Jure

**Comment by Cerovec** [comment]
Hi @jassiwalia001,

We're closing this issue as inactive. If you need any other assistance, please reopen this or create another issue.

Thanks!
Jurica.
