### ISSUE TITLE
Front Camera open by default

### ISSUE THREAD

**Issue by jassiwalia001** [BlinkID/blinkid-cordova#95]
I need to scan with my front camera, is blinkid provides this kind of functionality to change the camera ?

**Comment by jassiwalia001** [comment]
@jcular

**Comment by jassiwalia001** [comment]
any update over this ? @jcular

**Comment by jassiwalia001** [comment]
@i1E It will be great if you can please share ios plugin changes also.

**Comment by jcular** [comment]
Hi @jassiwalia001,

on iOS, if you are using `DocumentOverlaySettings` you should modify the [MBDocumentOverlaySettingsSerialization](https://github.com/BlinkID/blinkid-phonegap/blob/master/BlinkID/src/ios/sources/Overlays/Serialization/MBDocumentOverlaySettingsSerialization.m#L30) in the following way:
```objc
-(MBOverlayViewController *) createOverlayViewController:(NSDictionary *)jsonOverlaySettings recognizerCollection:(MBRecognizerCollection*)recognizerCollection delegate:(id<MBOverlayViewControllerDelegate>) delegate {
    // no settings deserialized at the moment
    MBDocumentOverlaySettings *sett = [[MBDocumentOverlaySettings alloc] init];
    sett.cameraSettings.cameraType = MBCameraTypeFront;
    self.delegate = delegate;
    return [[MBDocumentOverlayViewController alloc] initWithSettings:sett recognizerCollection:recognizerCollection delegate:self];
}
```

Kind regards,
Jure

**Comment by jassiwalia001** [comment]
Hi @jcular, this code doesn't worked for me. Can you please look into this ?
I have added the same code. I am using DocumentOverlaySettings.

**Comment by jassiwalia001** [comment]
Hi @jcular I am using 4.5.0 version of blinkid-phonegap

**Comment by jcular** [comment]
Hi @jassiwalia001,

that's the latest version, the same version I used to test i. Where in the project did you make the changes, are you sure you made the changes to the source that is used in your application?

Kind regards,
Jure

**Comment by jassiwalia001** [comment]
I made the changes in plugin file
-(MBOverlayViewController *) createOverlayViewController:(NSDictionary *)jsonOverlaySettings recognizerCollection:(MBRecognizerCollection*)recognizerCollection delegate:(id<MBOverlayViewControllerDelegate>) delegate {
    // no settings deserialized at the moment
    MBDocumentOverlaySettings *sett = [[MBDocumentOverlaySettings alloc] init];
    sett.cameraSettings.cameraType = MBCameraTypeFront;
    self.delegate = delegate;
    return [[MBDocumentOverlayViewController alloc] initWithSettings:sett recognizerCollection:recognizerCollection delegate:self];
}
![image](https://user-images.githubusercontent.com/13376362/50824611-0f3c3100-135d-11e9-8f0a-cf926f3f507b.png)

**Comment by jcular** [comment]
That looks correct and since you said you're using DocumentOveralyViewController this should work. Maybe try cleaning build completely and rebuilding the project.

Kind regards,
Jure

**Comment by jassiwalia001** [comment]
@jcular Its working now, but i have a issue in this as its not scanning back with front camera.

But its working if i am using Rear Camera. Any more configuration to do here please let me know.

**Comment by jassiwalia001** [comment]
any update on this @jcular

**Comment by Cerovec** [comment]
Hi @jassiwalia001,

Apologies for the delay with the answer. Since we found a way to scan using the front camera, we will close this issue for now. If you still face challenges when scanning the back side of your ID document, please open another issue dedicated to this so we can explore that specific issue.

Thanks,
Jurica.
